name: in_time_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.1.0
  pinput: ^5.0.1
#  flutter_otp_text_field: ^1.4.0+2
  easy_localization: ^3.0.7
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.7
#  google_maps_flutter: ^2.10.1
#  firebase_core: ^3.12.1
#  firebase_auth: ^5.5.1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  internet_connection_checker_plus: ^2.7.1
  json_annotation: ^4.8.1
  get_it: ^8.0.3
  dartz: ^0.10.1
  flutter_otp_text_field: ^1.4.0+2
  shared_preferences: ^2.5.3
  table_calendar: ^3.1.3
  intl: ^0.19.0
  webview_flutter: ^4.10.0
  google_fonts: ^6.3.2
  image_picker: ^1.2.1
  mobile_scanner: ^7.1.4
  local_auth: ^2.3.0
  animate_do: ^4.2.0
#  qr_code_scanner: ^1.0.1
#  qr_code_scanner: ^0.4.0
#  qr_code_scanner_plus: ^2.0.14

#  geocoding: ^3.0.0
#  flutter_animate: ^4.5.2
#  shimmer: ^3.0.0
#  webview_flutter: ^4.10.0
#  url_launcher: ^6.3.1
#  hyperpay_plugin: ^3.1.4
#  flutter_credit_card: ^4.1.0
#  carousel_slider: ^5.0.0
#  shared_preferences: ^2.5.3
#  encrypt: ^5.0.3
#  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.4
  json_serializable: ^6.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_green.png"